- type: job
  id: MedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  playTimeTracker: JobMedicalDoctor
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 2h # Corvax-RoleTime
  startingGear: DoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  # Corvax-Wega-SubRoles-start
  subRoles:
  - Surgeon
  - Geneticist
  - Coroner
  # Corvax-Wega-SubRoles-end
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: DoctorDay
    prototype: WehMedipen
  # Corvax-Wega-Surgery-start
  - !type:AddComponentSpecial
    components:
    - type: SurgicalSkill
  # Corvax-Wega-Surgery-end

- type: startingGear
  id: DoctorGear
  equipment:
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: MedicalDoctorChameleonOutfit
  job: MedicalDoctor
  equipment:
    head: ClothingHeadNurseHat
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesLatex
