- type: job
  id: Barber
  name: job-name-barber
  description: job-description-barber
  playTimeTracker: JobBarber
  requirements:
  - !type:OverallPlaytimeRequirement
      time: 7200 #2 hrs # Corvax-RoleTime
  startingGear: BarberGear
  icon: "JobIconBarber"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance

- type: startingGear
  id: BarberGear
  equipment:
    id: BarberPDA
    ears: ClothingHeadsetService
  storage:
    back:
    - BarberScissors
    - BarberRazor

- type: chameleonOutfit
  id: BarberChameleonOutfit
  job: Barber
  equipment:
    head: ClothingHeadHatTophat
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedBlack
    outerClothing: ClothingOuterApronBar
    gloves: ClothingHandsGlovesColorBlack
