- type: job
  id: Zookeeper
  name: job-name-zookeeper
  description: job-description-zookeeper
  playTimeTracker: JobZookeeper
  startingGear: ZookeeperGear
  icon: "JobIconZookeeper"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: MonkeyDay
    prototype: MonkeyCubeBox

- type: startingGear
  id: ZookeeperGear
  equipment:
    # shoes: ClothingShoesColorWhite # Corvax-Wega-Edit
    jumpsuit: ClothingUniformJumpsuitSafari
    head: ClothingHeadSafari
    id: ZookeeperPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ZookeeperChameleonOutfit
  job: Zookeeper
  equipment:
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterColorLightBrown
    neck: ClothingNeckScarfStripedBrown
    belt: ClothingBeltStorageWaistbag
    gloves: ClothingHandsGlovesColorBrown

