- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 15h
  - !type:DepartmentTimeRequirement
    department: Security
    time: 5h
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Muted
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
    - Brig
    - Detective
    - External
    - Medical
    - Security
    - Maintenance
    - Service
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: SurgicalSkill

- type: startingGear
  id: BrigmedicGear
  equipment:
    shoes: ClothingShoesBootsJackSecFilled
    gloves: ClothingHandsGlovesLatexSurgeon
    eyes: ClothingEyesHudMedSec
    id: BrigmedicPDA
    ears: ClothingHeadsetBrigmedic
    belt: ClothingBeltMedicalFilled
    pocket1: WeaponDisabler
  storage:
    back:
    - Flash
    - MedkitAdvancedFilled

- type: chameleonOutfit
  id: BrigmedicChameleonOutfit
  job: Brigmedic
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretSecurityMedic
    eyes: ClothingEyesHudMedSec
    mask: ClothingMaskBreathMedicalSecurity
    outerClothing: ClothingUniformJumpsuitBrigmedic
    neck: ClothingNeckScarfStripedRed
    gloves: ClothingHandsGlovesLatexSurgeon
